name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Obter data
        id: get-date
        run: echo "date=$(date -u +'%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache global do Buildozer
        uses: actions/cache@v4
        with:
          path: ~/.buildozer
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache do build local
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Build APK com Buildozer
        run: |
          yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
